package py.com.perseo.clientes.entities;

import py.com.perseo.exceptions.CustomMessageException;

public class ClienteTest {

	public  void clientefindAll() throws Exception, CustomMessageException {

//		List<Cliente> ret = new ArrayList<>();
//		for (int i = 0; i < 2; i++) {
//			Cliente cliente = new Cliente();
//			cliente.setIdcliente(1);
//			cliente.setNombreapellido("JUAN PEREZ");
//			cliente.setTipodocumento(new Tipodocumento("CI", "CEDULA DE IDENTIDAD"));
//			cliente.setNrodoc("3333333");
//			cliente.setSexo("M");
//			cliente.setFecnacimiento(new Date(System.currentTimeMillis()));
//			cliente.setLugarnacimiento("ASUNCION");
//			cliente.setNacionalidad("PARAGUAY");
//			cliente.setDireccion("MCAL. LOPEZ");
//			cliente.setTelefono("+595982111222");
////			cliente.setBarrio(new Barrio(1, "LOS LAURELES"));
////			cliente.setDistrito(new Distrito(1, "ASUNCION"));
////			cliente.setDepartamento(new Departamento(1, "CENTRAL"));
//			cliente.setLineacredito(new Double(5000000));
//			cliente.setEstado(true);
////			cliente.setEmpresa(new Empresa(1, "FUNDACION MICROSOL"));
////			cliente.setSucursal(new Sucursal(1, "MATRIZ"));
//			cliente.setCorreo("correo@host.com");
//			cliente.setWeb("www.cliente.com");
//			cliente.setEstadocivil("SO");
////			cliente.setOficial(new Usuario(1, "ROBERTO MACHADO"));
//			ret.add(cliente);
//		}

//		return ret;

	}

}
